# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47b29647c45ecbbd84977754d680ba8a499535794b1bebebe3339389c4ee5d932441a8eb3de84ecfda90d5189ba4433f4ca097dfd81670c3ff5e10ca48d77c9a

test:
  secret_key_base: 6743542b0f98451fb2e6bfd66e46d94a2c2a6ea8a9f48e2776e0e37dd052f59c66e48a8a484a5e2ee6463e5f5a3e80f3c21615260745ba9b4715814848c907e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
